import type { Metadata } from 'next';

// export const metadata: Metadata = {
//   title: 'Rwa',
//   description: 'Generated by create next app',
// };

interface Params {
  lobbyId: string;
}

export default async function Page({ params }: { params: Params }) {
  const { lobbyId } = await params;

  return <div className="a">Landing - lobbyId ID: {lobbyId}</div>;
}
