import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Rwa',
  description: 'Generated by create next app',
};

interface Params {
  roomId: string;
}

export default async function Page({ params }: { params: Params }) {
  const { roomId } = await params;

  return <div className="a">Landing - Room ID: {roomId}</div>;
}
